### ISSUE TITLE
LWMapRedOutputFormat not found

### ISSUE THREAD

**Issue by finch0001** [lucidworks/hadoop-solr#8] opened 2016-07-05 09:02 UTC
16/07/05 16:44:13 INFO mapreduce.Job: Task Id : attempt_1465785263925_0011_m_000000_0, Status : FAILED

Error: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.lucidworks.hadoop.io.LWMapRedOutputFormat not found

This is my jar file.
................................
com/lucidworks/hadoop/fusion/FusionPipelineClient$JacksonContentProducer.class
com/lucidworks/hadoop/io/LWMapReduceOutputFormat.class
com/lucidworks/hadoop/io/LWMapRedOutputFormat$1.class
com/lucidworks/hadoop/io/LWDocumentWritable.class
com/lucidworks/hadoop/io/LWDocumentProvider.class
com/lucidworks/hadoop/io/LWMapReduceOutputFormat$1.class
com/lucidworks/hadoop/io/LWDocument.class
com/lucidworks/hadoop/io/XMLInputFormat$XMLRecordReader.class
com/lucidworks/hadoop/io/FusionOutputFormat.class
com/lucidworks/hadoop/io/FusionInputFormat$FusionRecordReader.class
com/lucidworks/hadoop/io/FusionInputFormat.class
com/lucidworks/hadoop/io/FusionInputFormat$FusionInputSplit.class
com/lucidworks/hadoop/io/LWMapRedInputFormat$LWInputSplit.class
com/lucidworks/hadoop/io/FusionOutputFormat$DocBuffer.class
com/lucidworks/hadoop/io/XMLInputFormat.class
com/lucidworks/hadoop/io/LWMapRedInputFormat$LWRecordReader.class
com/lucidworks/hadoop/io/LWMapRedOutputFormat.class
com/lucidworks/hadoop/io/DateWritable.class
com/lucidworks/hadoop/io/LucidWorksWriter.class
com/lucidworks/hadoop/io/LWMapReduceOutputFormat$2.class
com/lucidworks/hadoop/io/FusionOutputFormat$FusionRecordWriter.class
com/lucidworks/hadoop/io/ZipFileInputFormat.class
com/lucidworks/hadoop/io/LWMapRedInputFormat.class
com/lucidworks/hadoop/LWDocumentModule.class
com/lucidworks/hadoop/utils/ZipFileRecordReader.class
com/lucidworks/hadoop/utils/CompressionHelper.class
................................

**Comment by ctargett** [comment] 2016-07-13 11:58
Duplicate of #9, so closing this one.

**Closed by ctargett** 2016-07-13 11:58 UTC
Labels: duplicate
